const store={
  page:'home',sub:'content',
  accounts:JSON.parse(localStorage.accounts||'[]'),activeAccount:localStorage.activeAccount||'',
  instances:JSON.parse(localStorage.instances||'[]'),
  settings:JSON.parse(localStorage.settings||'{"theme":"Dark","telemetry":false,"ram":"4G","java":"auto"}'),
  downloads:[],logs:['[launcher] ready'],filters:{type:'modpack',q:''}
};
const featured=[{name:'Fabulously Optimized',type:'modpack',desc:'FPS + QoL',dl:'8.2M',followers:'120k'},{name:'Adrenaline',type:'modpack',desc:'Perf visuals',dl:'5.7M',followers:'83k'},{name:'Sodium',type:'mod',desc:'Renderer',dl:'52M',followers:'390k'},{name:'Iris',type:'shader',desc:'Shaders',dl:'35M',followers:'270k'}];
const tags={categories:['adventure','combat','magic','optimization'],versions:['1.20.4','1.21.1','1.21.4'],loaders:['fabric','forge','neoforge','quilt']};
const q=s=>document.querySelector(s);const save=()=>{localStorage.accounts=JSON.stringify(store.accounts);localStorage.activeAccount=store.activeAccount;localStorage.instances=JSON.stringify(store.instances);localStorage.settings=JSON.stringify(store.settings)};
const uid=()=>crypto.randomUUID();
function offlineUuid(name){let h=0;for(let i=0;i<name.length;i++)h=(h*31+name.charCodeAt(i))>>>0;return`00000000-0000-3000-8000-${h.toString(16).padStart(12,'0').slice(-12)}`}
function fakeDownload(label){const id=uid();store.downloads.push({id,label,p:0});const t=setInterval(()=>{const d=store.downloads.find(x=>x.id===id);if(!d)return clearInterval(t);d.p=Math.min(100,d.p+10);if(d.p===100){store.logs.push(`[download] completed ${label}`);clearInterval(t)}render();},130)}
function nav(){return ['home','discover','library','instance','settings'].map(p=>`<div class="navbtn ${store.page===p?'active':''}" data-nav="${p}">${p[0].toUpperCase()}</div>`).join('')}
function accountPanel(){const a=store.accounts.find(x=>x.id===store.activeAccount);return`<div class=panel><h3>Playing as</h3><div>${a?a.username:'None selected'}</div><small>${a?a.uuid:''}</small><div class=row style="margin-top:8px"><button class=primary id=addacc>Offline</button><button disabled>Microsoft</button><button disabled>Ely.by</button></div></div>
<div class=panel><b>Accounts</b><div class=list>${store.accounts.map(a=>`<div class=item><div>${a.username}<div class=tag>${a.type}</div></div><div><button data-use="${a.id}">Use</button> <button data-delacc="${a.id}">X</button></div></div>`).join('')||'<small>No accounts</small>'}</div></div>
<div class=panel><b>Download Manager</b>${store.downloads.map(d=>`<div style="margin:8px 0">${d.label}<div class=progress><div class=bar style="width:${d.p}%"></div></div></div>`).join('')||'<small>No active downloads</small>'}</div>`}
function home(){return`<div class=top><h2>Welcome back!</h2><span class=status>${store.instances.length?'Ready to play':'No instances running'}</span></div>
<h3>Jump back in</h3><div class=cards>${store.instances.slice(0,4).map(i=>`<div class=card><span class=badge>${i.loader}</span><h4>${i.name}</h4><div class=tag>${i.version}</div><button class=primary data-play="${i.id}">Play</button></div>`).join('')||'<div class=card>No instances yet</div>'}</div>
<h3>Discover a modpack</h3><div class=cards>${featured.filter(f=>f.type==='modpack').map(card).join('')}</div><h3>Discover mods</h3><div class=cards>${featured.filter(f=>f.type!=='modpack').map(card).join('')}</div>`}
const card=f=>`<div class=card><span class=badge>${f.type}</span><h4>${f.name}</h4><p>${f.desc}</p><div class=tag>${f.dl} downloads • ${f.followers} followers</div><div class=row><button class=primary data-install="${f.name}">Install</button><button data-open="${f.name}">Details</button></div></div>`;
function discover(){const rows=featured.filter(f=>f.type.includes(store.filters.type.replace('pack',''))||store.filters.type==='all').filter(f=>f.name.toLowerCase().includes(store.filters.q.toLowerCase()));return`<div class=top><h2>Discover content</h2><div class=row><input id=search class=input placeholder="Search" value="${store.filters.q}"><select id=type><option ${sel('modpack')}>modpack</option><option ${sel('mod')}>mod</option><option ${sel('shader')}>shader</option><option ${sel('all')}>all</option></select></div></div>
<div class=hsplit><div><div class=list>${rows.map(f=>`<div class=item><div><b>${f.name}</b><div class=tag>${f.type} • ${f.desc}</div></div><button class=primary data-install="${f.name}">Install</button></div>`).join('')||'No results'}</div></div><aside class=panel><b>Filters</b><div class=tabs>${tags.categories.map(t=>`<span class=tab>${t}</span>`).join('')}</div><small>Game versions: ${tags.versions.join(', ')}</small><br><small>Loaders: ${tags.loaders.join(', ')}</small></aside></div>`}
function library(){return`<div class=top><h2>Instances</h2><div class=row><button id=create class=primary>Create</button><button id=importmr class=warn>Import .mrpack</button></div></div><div class=list>${store.instances.map(i=>`<div class=item><div><b>${i.name}</b><div class=tag>${i.loader} • ${i.version}</div></div><div><button data-view="${i.id}">Open</button> <button data-delinst="${i.id}">Delete</button></div></div>`).join('')||'<small>Empty library</small>'}</div>`}
function instanceDetail(){const i=store.instances.find(x=>x.id===store.currentInstance)||store.instances[0];if(!i)return '<h3>No instance selected</h3>';return`<div class=top><h2>${i.name}</h2><div class=row><button class=primary data-play="${i.id}">Play</button><button id=instset>Settings</button></div></div>
<div class=tabs>${['content','worlds','logs'].map(t=>`<div class="tab ${store.sub===t?'active':''}" data-sub="${t}">${t}</div>`).join('')}</div>
${store.sub==='content'?`<div class=list><div class=item><div>Sodium.jar<div class=tag>enabled</div></div><div><button>Disable</button> <button>Delete</button></div></div></div><button class=primary data-install="Content pack">Install content</button>`:''}
${store.sub==='worlds'?`<div class=panel>Worlds folder mock: <b>saves/</b></div>`:''}
${store.sub==='logs'?`<div class=panel style="white-space:pre-wrap">${store.logs.join('\n')}</div>`:''}`}
function settings(){return`<h2>Settings</h2><div class=grid><div class=panel><b>Appearance</b><div class=row><select id=theme><option ${opt('Dark')}>Dark</option><option ${opt('OLED')}>OLED</option><option ${opt('Light')}>Light</option></select><label><input type=checkbox id=tele ${store.settings.telemetry?'checked':''}> telemetry</label></div></div>
<div class=panel><b>Java & Memory</b><div class=row><input id=java value="${store.settings.java}"><input id=ram value="${store.settings.ram}"></div><small>Auto-detect + auto-download simulated.</small></div>
<div class=panel><b>Privacy</b><p class=muted>No telemetry by default.</p></div></div><button class=primary id=saveset>Save settings</button>`}
const sel=v=>store.filters.type===v?'selected':'';const opt=v=>store.settings.theme===v?'selected':'';
const pageView=()=>({home,discover,library,instance:instanceDetail,settings}[store.page]||home)();
function render(){document.getElementById('app').innerHTML=`<div class=app><aside class=sidebar><div class=logo>PL</div>${nav()}</aside><main class=main>${pageView()}</main><aside class=right>${accountPanel()}</aside></div>`;bind()}
function bind(){document.querySelectorAll('[data-nav]').forEach(n=>n.onclick=()=>{store.page=n.dataset.nav;render()});q('#addacc')?.addEventListener('click',()=>{const u=prompt('Offline username');if(!u)return;const id=uid();store.accounts.push({id,type:'offline',username:u,uuid:offlineUuid('OfflinePlayer:'+u)});store.activeAccount=id;save();render()});
document.querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>{store.activeAccount=b.dataset.use;save();render()});document.querySelectorAll('[data-delacc]').forEach(b=>b.onclick=()=>{store.accounts=store.accounts.filter(a=>a.id!==b.dataset.delacc);if(store.activeAccount===b.dataset.delacc)store.activeAccount='';save();render()});
q('#search')?.addEventListener('input',e=>{store.filters.q=e.target.value;render()});q('#type')?.addEventListener('change',e=>{store.filters.type=e.target.value;render()});
q('#create')?.addEventListener('click',()=>{const name=prompt('Instance name?');if(!name)return;const loader=prompt('Loader? vanilla/fabric/forge','fabric')||'fabric';const version=prompt('Version?','1.21.1')||'1.21.1';store.instances.push({id:uid(),name,loader,version});save();render()});
q('#importmr')?.addEventListener('click',()=>{const name=prompt('.mrpack name','Imported Pack')||'Imported Pack';store.instances.push({id:uid(),name,loader:'fabric',version:'1.21.1'});fakeDownload(`${name} files`);save();render()});
document.querySelectorAll('[data-delinst]').forEach(b=>b.onclick=()=>{store.instances=store.instances.filter(i=>i.id!==b.dataset.delinst);save();render()});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{store.currentInstance=b.dataset.view;store.page='instance';render()});
document.querySelectorAll('[data-sub]').forEach(b=>b.onclick=()=>{store.sub=b.dataset.sub;render()});document.querySelectorAll('[data-install]').forEach(b=>b.onclick=()=>fakeDownload(b.dataset.install));
document.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>{store.logs.push(`[launch] launching ${b.dataset.play} with --accessToken 0 --userType legacy`);alert('Launch simulated. See Logs tab.');});
q('#saveset')?.addEventListener('click',()=>{store.settings.theme=q('#theme').value;store.settings.telemetry=q('#tele').checked;store.settings.java=q('#java').value;store.settings.ram=q('#ram').value;save();alert('Saved')});}
render();
