import { invoke } from '@tauri-apps/api/core';
export type OfflineAccount={id:string;username:string;kind:'offline'};
export type AccountsState={active_account_id:string|null;accounts:OfflineAccount[]};
export type ModrinthProject={id?:string;project_id?:string;slug?:string;title:string;description:string;body?:string;icon_url:string|null;downloads?:number;followers?:number;project_type:string;author?:string;categories?:string[]};
export type ModrinthVersion={id:string;name:string;version_number:string;game_versions:string[];loaders:string[];date_published:string};
export type SearchResponse={hits:ModrinthProject[];total_hits?:number};
export type InstanceSummary={id:string;name:string;mc_version:string;loader:string;last_played?:string|null};
export type InstancesState={instances:InstanceSummary[]};
export const getAccounts=()=>invoke<AccountsState>('get_accounts');
export const addOfflineAccount=(username:string)=>invoke<AccountsState>('add_offline_account',{username});
export const deleteAccount=(accountId:string)=>invoke<AccountsState>('delete_account',{accountId});
export const setActiveAccount=(accountId:string)=>invoke<AccountsState>('set_active_account',{accountId});
export const searchProjects=(args:any)=>invoke<SearchResponse>('search_projects',args);
export const getProject=(idOrSlug:string)=>invoke<ModrinthProject>('get_project',{idOrSlug});
export const getProjectVersions=(projectId:string)=>invoke<ModrinthVersion[]>('get_project_versions',{projectId});
export const listInstances=()=>invoke<InstancesState>('list_instances');
export const createInstance=(name:string,mcVersion:string,loader:string)=>invoke<InstancesState>('create_instance',{name,mcVersion,loader});
export const deleteInstance=(instanceId:string)=>invoke<InstancesState>('delete_instance',{instanceId});
